// Backend/routes/documentRequestRoutes.js
//
// Handles "Official Document Request" submissions — e.g. Archives Nationales,
// DCPJ, OAVCT, DGI. Uses the same Transcript collection as the university
// evaluation flow (requestType: "official_document_request"), but requires
// identity fields + a government ID upload, and does NOT let the student
// pick the institution — your admin team assigns it afterward, same as
// university requests.
const express = require("express");
const multer = require("multer");
const jwt = require("jsonwebtoken");
const pdfParse = require("pdf-parse");

const Transcript = require("../models/Transcript");
const { buildKey, uploadBuffer, signedGetUrl } = require("../services/r2Storage");

const router = express.Router();

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 25 * 1024 * 1024 }, // 25MB each
});

function requireStudent(req) {
  const token = req.headers.authorization?.split(" ")[1];
  if (!token) return { error: { code: 401, body: { error: "Unauthorized" } } };
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    return { studentId: decoded.id };
  } catch {
    return { error: { code: 401, body: { error: "Unauthorized" } } };
  }
}

// Hardcoded for now (per your call) — mirrors the taxonomy you sketched out.
// If this grows a lot, it's a natural candidate to move into a DB-managed
// collection later, same pattern as Institution.
const DOCUMENT_TYPES = {
  academic: ["Transcript", "Diploma", "Degree Certificate", "Enrollment Letter", "Academic Record"],
  civil: ["Birth Certificate", "Marriage Certificate", "Death Certificate", "Divorce Certificate", "National ID Records"],
  professional: ["Medical License", "Engineering License", "Bar Certificate", "Professional Certifications"],
  government: ["Police Certificate", "Tax Certificate", "Business Registration", "Others"],
};

// ─────────────────────────────────────────────
// POST /api/document-requests/submit
// ─────────────────────────────────────────────
router.post(
  "/submit",
  upload.fields([
    { name: "files", maxCount: 10 },          // optional supporting documents
    { name: "identityDocument", maxCount: 1 }, // required government ID
  ]),
  async (req, res) => {
    try {
      const auth = requireStudent(req);
      if (auth.error) return res.status(auth.error.code).json(auth.error.body);
      const studentId = auth.studentId;

      const { documentCategory, documentType, legalName, dateOfBirth, idNumber, notes } = req.body;

      if (!documentCategory || !DOCUMENT_TYPES[documentCategory]) {
        return res.status(400).json({ error: "Invalid document category" });
      }
      if (!documentType || !DOCUMENT_TYPES[documentCategory].includes(documentType)) {
        return res.status(400).json({ error: "Invalid document type for that category" });
      }
      if (!legalName || !dateOfBirth) {
        return res.status(400).json({ error: "Legal name and date of birth are required" });
      }

      const identityFile = req.files?.identityDocument?.[0];
      if (!identityFile) {
        return res.status(400).json({ error: "A government ID upload is required for document requests" });
      }

      // The actual document being requested (e.g. an existing copy of the birth
      // certificate, a scan of the license, etc.) is REQUIRED — this is the file
      // that shows up in the admin/institution "Documents" list, same as the
      // university evaluation flow. Skipping this was the bug that made
      // submissions look empty everywhere.
      const supportingFiles = req.files?.files || [];
      if (supportingFiles.length === 0) {
        return res.status(400).json({ error: "Please upload at least one copy of the document you are requesting" });
      }


      // Create the request first (submissionId generated by model pre-validate)
      const transcript = new Transcript({
        student: studentId,
        submissionMethod: "digital",
        requestType: "official_document_request",
        documentCategory,
        documentType,
        notes: notes || "",
        applicantIdentity: {
          legalName,
          dateOfBirth,
          idNumber: idNumber || "",
        },
        documents: [],
      });

      await transcript.save();
      const submissionId = transcript.submissionId;

      // Optional supporting documents (e.g. a prior certificate, old ID copy, etc.)
      const documents = await Promise.all(
        supportingFiles.map(async (file) => {
          let pageCount = 1;
          if (file.mimetype === "application/pdf") {
            const pdfData = await pdfParse(file.buffer);
            pageCount = pdfData.numpages || 1;
          }

          const key = buildKey({
            prefix: "document-request-support",
            requestId: submissionId,
            originalName: file.originalname,
          });

          await uploadBuffer({ key, buffer: file.buffer, contentType: file.mimetype });

          return {
            filename: file.originalname,
            mimetype: file.mimetype,
            bucket: process.env.R2_BUCKET,
            key,
            pageCount,
          };
        })
      );

      // Identity document — stored separately, only surfaced in admin/institution review
      const idKey = buildKey({
        prefix: "identity-documents",
        requestId: submissionId,
        originalName: identityFile.originalname,
      });
      await uploadBuffer({ key: idKey, buffer: identityFile.buffer, contentType: identityFile.mimetype });

      transcript.documents = documents;
      transcript.identityDocument = {
        filename: identityFile.originalname,
        mimetype: identityFile.mimetype,
        bucket: process.env.R2_BUCKET,
        key: idKey,
        size: identityFile.size,
      };
      await transcript.save();

      return res.json({
        message: "Document request submitted successfully",
        submissionId,
      });
    } catch (error) {
      console.error("Document request submission error:", error);
      res.status(500).json({ error: "Server error" });
    }
  }
);

// ─────────────────────────────────────────────
// GET /api/document-requests/mine
// ─────────────────────────────────────────────
router.get("/mine", async (req, res) => {
  try {
    const auth = requireStudent(req);
    if (auth.error) return res.status(auth.error.code).json(auth.error.body);

    const submissions = await Transcript.find({
      student: auth.studentId,
      requestType: "official_document_request",
    })
      .select("-documents.buffer")
      .sort({ createdAt: -1 });

    return res.json(submissions);
  } catch (err) {
    console.error(err);
    return res.status(401).json({ error: "Invalid token" });
  }
});

// ─────────────────────────────────────────────
// GET /api/document-requests/:id/document/:idx/download
// Student downloads their own submitted document copy
// ─────────────────────────────────────────────
router.get("/:id/document/:idx/download", async (req, res) => {
  try {
    const auth = requireStudent(req);
    if (auth.error) return res.status(auth.error.code).json(auth.error.body);

    const { id, idx } = req.params;
    const i = Number(idx);

    const t = await Transcript.findOne({
      _id: id,
      student: auth.studentId,
      requestType: "official_document_request",
    }).select("documents");

    if (!t) return res.status(404).json({ error: "Not found" });
    if (!Array.isArray(t.documents) || Number.isNaN(i) || i < 0 || i >= t.documents.length) {
      return res.status(400).json({ error: "Invalid document index" });
    }

    const doc = t.documents[i];
    if (!doc.key) return res.status(404).json({ error: "File not available" });

    const url = await signedGetUrl({ key: doc.key });
    return res.json({ url });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: "Failed to fetch download link" });
  }
});

// ─────────────────────────────────────────────
// DELETE /api/document-requests/:id/document/:idx
// Student deletes an uploaded document copy — only allowed while unpaid.
// (The identity document / government ID is never deletable this way.)
// ─────────────────────────────────────────────
router.delete("/:id/document/:idx", async (req, res) => {
  try {
    const auth = requireStudent(req);
    if (auth.error) return res.status(auth.error.code).json(auth.error.body);

    const { id, idx } = req.params;
    const i = Number(idx);

    const submission = await Transcript.findOne({
      _id: id,
      student: auth.studentId,
      requestType: "official_document_request",
    });

    if (!submission) return res.status(404).json({ error: "Submission not found" });

    if (submission.paymentStatus === "paid") {
      return res.status(403).json({
        error: "This request has already been paid and its documents can no longer be deleted.",
      });
    }

    if (!Array.isArray(submission.documents) || Number.isNaN(i) || i < 0 || i >= submission.documents.length) {
      return res.status(400).json({ error: "Invalid document index" });
    }

    submission.documents.splice(i, 1);

    if (submission.documents.length === 0) {
      // Same rule as the university flow: a request needs at least one document
      // copy, so removing the last one deletes the whole (unpaid) request.
      await Transcript.deleteOne({ _id: submission._id });
      return res.json({
        message: "Document removed. The request had no remaining documents, so it was deleted.",
        deletedSubmission: true,
      });
    }

    await submission.save();
    return res.json({ message: "Document removed successfully.", deletedSubmission: false });
  } catch (err) {
    console.error("Delete document request file error:", err);
    return res.status(500).json({ error: "Failed to delete document." });
  }
});

module.exports = router;
